version: "2"
services:
  gitlab:
    image: docker.artifactory/gitlab:gitlab_latest
    container_name: gitlab
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '9090:9090'
